# Generated by Django 4.0.3 on 2022-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerdata',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='interval',
            field=models.SmallIntegerField(
                choices=[(0, '1m'), (1, '5m'), (2, '15m'), (3, '30m'), (4, '1h'), (5, '4h'), (6, '1d'), (7, '1w')],
                default=1),
            preserve_default=False,
        ),
    ]
