# Generated by Django 4.0.3 on 2022-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0004_candlestick_delete_tickerdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candlestick',
            unique_together={('pair', 'interval')},
        ),
    ]
