# Generated by Django 4.0.3 on 2022-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('timeframe', models.SmallIntegerField(
                    choices=[(0, 60), (1, 300), (2, 1800), (3, 3600), (4, 14400), (5, 86400), (6, 604800)])),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
