# Generated by Django 4.0.3 on 2022-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0002_remove_tickerdata_timeframe_tickerdata_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdata',
            name='interval',
            field=models.CharField(
                choices=[(0, '1m'), (1, '5m'), (2, '15m'), (3, '30m'), (4, '1h'), (5, '4h'), (6, '1d'), (7, '1w')],
                max_length=3),
        ),
    ]
