# Generated by Django 4.0.3 on 2022-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0003_alter_tickerdata_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('interval', models.CharField(
                    choices=[(0, '1m'), (1, '5m'), (2, '15m'), (3, '30m'), (4, '1h'), (5, '4h'), (6, '1d'), (7, '1w')],
                    max_length=3)),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
        migrations.DeleteModel(
            name='TickerData',
        ),
    ]
