# Generated by Django 4.0.4 on 2022-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_orderbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='exchange',
            field=models.CharField(default='gate_io', max_length=10),
        ),
    ]
