# Generated by Django 4.0.4 on 2022-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_orderbook_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='interval',
            field=models.CharField(choices=[(0, '1m'), (1, '5m'), (2, '15m'), (3, '30m'), (4, '1h'), (5, '4h'), (6, '1d'), (7, '1w')], default=60, max_length=3),
            preserve_default=False,
        ),
    ]
