# Generated by Django 4.0.4 on 2022-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_orderbook_interval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candlestick',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='exchange',
            field=models.CharField(choices=[(0, 'gate_io'), (1, 'binance')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candlestick',
            unique_together={('pair', 'interval', 'datetime', 'exchange')},
        ),
    ]
